# ?????
spring.datasource.url=jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=urPassword
spring.datasource.hikari.maximum-pool-size=10

# JPA ??
# ????/????????????
spring.jpa.hibernate.ddl-auto=update
# ?? SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true # ??? SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# MyBatis ??
#mybatis.mapper-locations=classpath:mapper/StudentMapper.xml  # Mapper XML ????
#mybatis.type-aliases-package=ORM.entity   # ?????????
mybatis.mapper-locations=classpath:ORM/OneToManyExample/Mybatis/StudentMapper.xml
mybatis.type-aliases-package=ORM.OneToManyExample.Mybatis
# ????????
mybatis.configuration.map-underscore-to-camel-case=true